### ISSUE TITLE
[bug] can't draw with default cmd

### ISSUE THREAD

**Issue by MMNavetty** [cocoon2wong/Vertical#4]
I get an error while trying to draw result with the basic test command provided in the github.

step to reproduce : launch python main.py --model V --loada ./weights/vertical/a_sdd --loadb l --draw_results 1 --draw_distribution 2

error : in __dataset.py, VideoClip.get try to access a subset .plist with the name of the main set.

complete error message :

Traceback (most recent call last):
  File "/folder_path/main.py", line 45, in <module>
    main(sys.argv)
  File "/folder_path/main.py", line 41, in main
    s(terminal_args=args).train_or_test()
  File "/folder_path/silverballers/__baseSilverballers.py", line 153, in train_or_test
    self.run_test()
  File "/folder_path/codes/training/__structure.py", line 370, in run_test
    self.__test(agents, dataset=self.args.test_set)
  File "/folder_path/codes/training/__structure.py", line 499, in __test
    self.write_test_results(outputs=outputs,
  File "/folder_path/codes/training/__structure.py", line 633, in write_test_results
    tv = Visualization(dataset=dataset)
  File "/folder_path/codes/training/__vis.py", line 64, in __init__
    self.DM = VideoClip.get(dataset)
  File "/folder_path/codes/dataset/__dataset.py", line 55, in get
    raise FileNotFoundError(
FileNotFoundError: Dataset file `sdd`.plist NOT FOUND.

I don't think this error come from my configuration since i pretty much changed nothing. Does everyone have the same problem ?
Thanks in advance,
MM

**Comment by MMNavetty** [comment]
after some research, it's because of --test_mode=mix. the assertion checking the mode don't work so i took some time to find the issue.

**Comment by MMNavetty** [comment]
Since i'm here, i think override the terminal args with the json args is very counter-intuitive and is bound to make many people struggling to use the code. I think it's best to make the priority in order (from low to high) : default values / json values / terminal values.
codes/args/__args.py l 40-45
Best,
MM

**Comment by cocoon2wong** [comment]
Hi @MMNavetty !

If you want to draw visualized results on SDD dataset, you should specify the name of video clip.
Specifically, the name of SDD clips should be given in the format of `name+video`like `coupa0`, `bookstore0`, `little0`, ... .
For example, you can draw the results on `little0` via the following command (remember to rename and put the corresponding video into `./videos/sdd_little_0.mov`):

```bash
python main.py --model V --loada ./weights/vertical/a_sdd --loadb l --draw_results 1 --draw_distribution 2 --test_mode one --force_set little0
```

In addition, the priority of args varies depending on the type `static` and `dynamic`, as you can see in the following codes:
https://github.com/cocoon2wong/Vertical/blob/8d2c8e82dead16fc6316252bf7659345cfc8eb12/codes/args/__args.py#L119-L129

The `static` indicates that the arg can not be changed once after training.
On the contrary, the `dynamic` indicates it can be changed via the user input from the terminal. (codes will read args as your mentioned `default values / json values / terminal values` order.)

We have revised the README and added detailed visualization instructions so as to reduce confusion for readers.
Thank you very much for your question!😄
