### ISSUE TITLE
Guidance Map

### ISSUE THREAD

**Issue by SaoDiSengA** [cocoon2wong/Vertical#6]
hello，how can i get more guidance map？
your code just find ZARA‘s trajMap.png

**Comment by NorthOcean** [comment]
Hi! If you want to get other guidance maps, you should run the complete model (not ` --loadb l`) on other datasets.
For instance,
```bash
for dataset in eth hotel univ zara1 zara2 sdd
  python main.py \
    --model V \
    --loada ./weights/vertical/a_${dataset} \
    --loadb ./weights/vertical/b_${dataset}
```
