### ISSUE TITLE
Missing frame 0 in ETH-hotel

### ISSUE THREAD

**Issue by ericaweng** [cocoon2wong/Vertical#7]
Thank you for your good work in this paper.
In the data split used in [your ETH-hotel](https://github.com/cocoon2wong/Vertical/blob/main/data/eth/hotel/true_pos_.csv) (which you say is the same as that in SimAug, etc.), frame 0 seems to be missing. (Compare with [the data split](https://github.com/StanfordASL/Trajectron-plus-plus/blob/master/experiments/pedestrians/raw/hotel/test/biwi_hotel.txt#L1-L10) used in Trajectron (and S-GAN, Y-Net, etc.)) I did a scan of the entire csv file, and I may have missed it, but I don't believe it's there.
In [the issue with @MeiliMa](https://github.com/cocoon2wong/Vertical/issues/1) you mention the only difference between the two versions is in the ETH-univ sampling rate. Of course missing one frame in ETH-hotel is a small difference, but is it possible there are other differences between the version used by SimAug and you, and the version used by Trajectron++, S-GAN, Y-Net, and the other methods you compare to in the paper, that make it an unfair comparison?

**Comment by cocoon2wong** [comment]
Hi @ericaweng!
Thanks for your comments!
Please note that our ETH-UCY files come from [SR-LSTM (CVPR2019) / E-SR-LSTM (TPAMI2020)](https://github.com/zhangpur/SR-LSTM).
We have compared other sub-datasets in your mentioned links. Specifically, in eth-univ's data, we have the same data as in the link except for frame 0 (from frame 10 to frame 18060). We also compared the data of zara and univ in your link (including starting frame and agent ID).
Please note that we have pointed out that the SDD data comes from their original data [Stanford Drone Dataset](https://cvgl.stanford.edu/projects/uav_data/) and not from any other split (e.g. only pedestrian trajectories are used in TrajNet). 
If you think there is a discrepancy in the data, we would appreciate it if you could specifically point out why.

**Comment by cocoon2wong** [comment]
I think this issuek may have been resolved due to the long period of time without a response. If you have new questions please also open a new issue. We appreciate your questions！
